/**
 * build-framer.js
 * Bundles the modular project into a single FramerApp.jsx
 * compatible with Framer Code Components (no bundler needed).
 *
 * Strategy:
 *  1. Read each source file in dependency order
 *  2. Strip all import/export statements
 *  3. Concatenate with section headers
 *  4. Wrap in the standard Framer React entry point
 */

const fs   = require('fs');
const path = require('path');

const root = path.join(__dirname, '..');
const dist = path.join(root, 'dist');

if (!fs.existsSync(dist)) fs.mkdirSync(dist);

// ── Helpers ────────────────────────────────────────────────
function read(rel) {
  const full = path.join(root, rel);
  if (!fs.existsSync(full)) { console.warn(`  ⚠  Not found, skipping: ${rel}`); return ''; }
  return fs.readFileSync(full, 'utf-8');
}

function strip(code) {
  return code
    .replace(/^import\s+.*?from\s+['"][^'"]+['"]\s*;?\s*$/gm, '')   // import ... from '...'
    .replace(/^export\s+default\s+/gm, '')                            // export default X
    .replace(/^export\s+(const|function|class|let|var)\s+/gm, '$1 ') // export const X → const X
    .replace(/^export\s+\{[^}]*\}\s*;?\s*$/gm, '')                   // export { A, B }
    .trim();
}

function section(label, code) {
  const stripped = strip(code);
  if (!stripped) return '';
  return `\n// ${'─'.repeat(56)}\n// ${label}\n// ${'─'.repeat(56)}\n${stripped}\n`;
}

const files = [
  ['src/tokens.js',                          'TOKENS'],
  ['src/icons.jsx',                          'ICONS'],
  ['src/components/Primitives.jsx',          'PRIMITIVES — Badge, GlowBtn'],
  ['src/components/ParticlesBg.jsx',        'INTERACTIVE PARTICLES BACKGROUND'],
  ['src/components/NavBar.jsx',              'NAVIGATION BAR'],
  ['src/components/Panel.jsx',              'PANEL WRAPPER'],
  ['src/components/Landing.jsx',             'MAIN LANDING'],
  ['src/components/PanelNosotros.jsx',       'PANEL — NOSOTROS'],
  ['src/components/PanelServicios.jsx',      'PANEL — SERVICIOS'],
  ['src/components/PanelSocios.jsx',         'PANEL — SOCIOS'],
  ['src/components/PanelContacto.jsx',       'PANEL — CONTACTO'],
  ['src/components/PanelLocalizacion.jsx',   'PANEL — LOCALIZACIÓN'],
  ['src/components/PanelSoporte.jsx',         'PANEL — SOPORTE'],
];

console.log('🚀 Iniciando compilación para Framer...\n');

let body = '';
for (const [file, label] of files) {
  const code = read(file);
  body += section(label, code);
  console.log(`  ✓  ${file}`);
}

// App root logic (strip imports, keep function body)
const appRaw = strip(read('App.jsx'));

// ── Assemble final file ────────────────────────────────────
const output = `// ============================================================
// B2Tech — Framer Code Component
// Auto-generated by build-framer.js — DO NOT EDIT DIRECTLY
// Edit the source files in src/ and run: npm run build
// ============================================================
import React, { useState, useCallback, useEffect, useRef } from 'react';
import { motion, AnimatePresence, useAnimation } from 'framer-motion';

${body}

// ────────────────────────────────────────────────────────────
// APP ROOT
// ────────────────────────────────────────────────────────────
${appRaw}

// Required Framer export
export default App;
`.trim();

const dest    = path.join(dist, 'FramerApp.jsx');
const sizeKb  = (Buffer.byteLength(output, 'utf-8') / 1024).toFixed(1);

fs.writeFileSync(dest, output, 'utf-8');

console.log(`\n✅  dist/FramerApp.jsx — ${sizeKb} KB — listo para Framer`);
console.log('   Importa este archivo como Code Component en tu proyecto Framer.\n');
